apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mykube-rs
spec:
  replicas: 2
  selector:
    matchLabels:
      env: production
  template:
    metadata:
      name: mypod
      labels:
        env: production
    spec:
      containers:
        - name: mypod-os
          image: httpd 
